services:
  proxy:
    build: ../go-proxy/go-proxy.dockerfile
    ports:
      - "8080:8080"  # Mapowanie portu hosta na port kontenera
    environment:
      - SERVER_PORT=8080
      - REDIS_ADDR=redis:6379  # Redis zdefiniowany w tej samej sieci
    depends_on:
      - redis  # Serwer proxy musi poczekać na uruchomienie Redisa

  redis:
    image: "redis:6.2-alpine"
    ports:
      - "6379:6379"  # Port dla Redisa
    command: ["redis-server", "--appendonly", "yes"]  # Użycie trwałego zapisu danych
    volumes:
      - redis_data:/data  # Trwałe przechowywanie danych w Redis

volumes:
  redis_data:
