version: '3.8'

services:
  proxy:
    build:
      context: ./../go-proxy
      dockerfile: go-proxy.dockerfile
    ports:
      - "8080:8080"  
    environment:
      - SERVER_PORT=8080
      - REDIS_ADDR=redis:6379  
    depends_on:
      - redis  

  proxy-analyzer:
    build: .
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - .:/app
    command: python scripts/analyze_requests.py

  redis:
    image: "redis:6.2-alpine"
    ports:
      - "6379:6379"  
    command: ["redis-server", "--appendonly", "yes"]  
    volumes:
      - redis_data:/data  

volumes:
  redis_data:
